---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: false
    enableSnippets: true
    image:
      repository: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress
      tag: 2.3.0
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    serviceAccount:
      imagePullSecretName: regcred
  prometheus:
    create: true
